Dockerized object_detection package
atom-robotics-lab/ros-perception-pipeline pull request #32
Opened 2023-07-19 07:23 UTC by topguns837

- [x] Added Dockerfile
- [x] Added bash scripts to start and stop the docker container
- [x]  Resolved https://github.com/atom-robotics-lab/ros-perception-pipeline/issues/30
- [x] Added for displaying logs :https://github.com/atom-robotics-lab/ros-perception-pipeline/blob/23c06d5bbf826ce5e68d6cda789d7f2c5836ac0b/object_detection/launch/object_detection.launch.py#L37

2023-09-16 19:23 UTC, jasmeet0915 commented on Dockerfile
> +    vim \
Why is Vim needed to be installed? I think nano should be there by default

2023-09-16 19:25 UTC, jasmeet0915 commented on Dockerfile
> +ENV RMW_IMPLEMENTATION rmw_cyclonedds_cpp
I think initially we should go with the default DDS. What do you say @topguns837?

2023-09-27 17:29 UTC, topguns837 commented on Dockerfile
> +    vim \
Nano wasn't installed by default. I have added the code to install nano in the Dockerfile

2023-09-29 11:16 UTC, jasmeet0915 commented on Dockerfile
> +RUN apt install -y ros-humble-cv-bridge
Now that #36 is merged, I think you should use `rosdep` to install all the dependencies here

2023-10-02 05:33 UTC, NOEMOJI041 requested changes

2023-10-02 05:33 UTC, NOEMOJI041 commented on docker_scripts/run_devel.sh
@topguns837 Nvidia ENV is not included in this file, the GPU was not identified. Also, can we add an arg to remove the container after use so that when we launch it again with this file, we didn't get the error container object_detection exists?

2023-10-02 05:33 UTC, NOEMOJI041 commented on Dockerfile
@topguns837 Can we add args in this file so that cuda version can be installed according to the gpu driver version installed? as in my case 525 is installed and it is incompatible with cuda version 12.2.

2023-11-11 19:14 UTC, topguns837 commented on Dockerfile
Done at : https://github.com/atom-robotics-lab/ros-perception-pipeline/blob/baa2700d826a2e9a2da3b4eee8aafd17b9bafe83/Dockerfile#L5

@NOEMOJI041

2023-11-12 16:53 UTC, topguns837 commented on docker_scripts/run_devel.sh
- [x] GPU is not being utilized while using YOLOv8 and RetinaNet
- [x] The docker container is being removed after it is closed

2023-11-12 16:55 UTC, NOEMOJI041 approved these changes

2023-11-12 17:03 UTC, topguns837 commented
These are some of the recent developments : 

- [x] Using NVIDIA-CUDA's docker image as base
- [x] Taking CUDA Version as an argument in [run_devel.sh](https://github.com/atom-robotics-lab/ros-perception-pipeline/blob/9139277267a22cd1ba9b7a1115cb1041d284d11e/docker_scripts/run_devel.sh#L15C9-L15C9) (default set to 11.8)
- [x] Feature to build the image if it doesn't exist in [run_devel.sh](https://github.com/atom-robotics-lab/ros-perception-pipeline/blob/9139277267a22cd1ba9b7a1115cb1041d284d11e/docker_scripts/run_devel.sh#L22C6-L22C6)
- [x] Feature to open bash in the container if it is already running in [run_devel.sh](https://github.com/atom-robotics-lab/ros-perception-pipeline/blob/9139277267a22cd1ba9b7a1115cb1041d284d11e/docker_scripts/run_devel.sh#L28C9-L28C9)
- [x] Feature to close the container once it is exited in [run_devel.sh](https://github.com/atom-robotics-lab/ros-perception-pipeline/blob/9139277267a22cd1ba9b7a1115cb1041d284d11e/docker_scripts/run_devel.sh#L34C8-L34C8)   
- [x] Updated Readme with the new instructions regarding Docker

2023-11-12 17:05 UTC, NOEMOJI041 commented
@topguns837 @jasmeet0915 Verified and Tested from my end!!!!👍👍

2024-02-04 19:36 UTC, merged