added package depend
atom-robotics-lab/ros-perception-pipeline pull request #36
Opened 2023-09-17 16:32 UTC by NOEMOJI041

Updated Package.xml
- cv_bridge
- vision_msg

perception_bringup
-cv_bridge
-vision_msg
-ros_gz_bridge

2023-09-18 09:59 UTC, jasmeet0915 commented
@NOEMOJI041 Could you update the installation steps in the README.md for using rosdep to install the dependencies before building the package?

2023-09-18 12:18 UTC, jasmeet0915 requested changes

2023-09-18 12:37 UTC, NOEMOJI041 commented on perception_bringup/package.xml
> +  <exec_depend>cv_bridge</exec_depend>
removed in commit [0ab0c7f](https://github.com/atom-robotics-lab/ros-perception-pipeline/pull/36/commits/0ab0c7fcb4a78a08bce09ffdd358e8a4f1b3f47f)

2023-09-18 12:37 UTC, NOEMOJI041 commented on perception_bringup/package.xml
> +  <exec_depend>vision_msgs</exec_depend>
remove in commit [0ab0c7f](https://github.com/atom-robotics-lab/ros-perception-pipeline/pull/36/commits/0ab0c7fcb4a78a08bce09ffdd358e8a4f1b3f47f)

2023-09-18 12:39 UTC, NOEMOJI041 commented on perception_bringup/package.xml
> +  <exec_depend>ros_gz_bridge</exec_depend>
Added in commit [0ab0c7f](https://github.com/atom-robotics-lab/ros-perception-pipeline/pull/36/commits/0ab0c7fcb4a78a08bce09ffdd358e8a4f1b3f47f) 
Thanks for advice.

2023-09-18 12:53 UTC, NOEMOJI041 commented
> @NOEMOJI041 Could you update the installation steps in the README.md for using rosdep to install the dependencies before building the package?

Added Readme for installation of dependencies with commit [0ab0c7f](https://github.com/atom-robotics-lab/ros-perception-pipeline/pull/36/commits/91ef460b282ab006a441707632bd77a40a8a2957)

2023-09-18 14:05 UTC, jasmeet0915 commented on README.md
>        git clone git@github.com:atom-robotics-lab/ros-perception-pipeline.git
Since all the commands in the steps below need to be executed from the `percep_ws` directory, can you update this step to clone the repo directly into `src` without cd'ing into it?

2023-09-18 15:22 UTC, NOEMOJI041 commented on README.md
>        git clone git@github.com:atom-robotics-lab/ros-perception-pipeline.git
Resolved with [f816334](https://github.com/atom-robotics-lab/ros-perception-pipeline/pull/36/commits/f8163347aa5d439cdade49c78508e8ed77f8a6d9)

2023-09-24 10:35 UTC, NOEMOJI041 commented
Added PYTHON PATH note with commit [f0eb8bf](https://github.com/atom-robotics-lab/ros-perception-pipeline/pull/36/commits/f0eb8bfb9301ea28411424c6daf0669915b2fd55)

2023-09-29 11:14 UTC, jasmeet0915 approved these changes

2023-09-29 11:15 UTC, merged